postgres:
  container_name: postgres
  image: postgres
  restart: unless-stopped
  environment:
    - TZ=${TZ:-Etc/UTC}
    - POSTGRES_USER=${POSTGRES_USER:-postuser}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-IOtSt4ckpostgresDbPw}
    - POSTGRES_DB=${POSTGRES_DB:-postdb}
  ports:
    - "5432:5432"
  volumes:
    - ./volumes/postgres/data:/var/lib/postgresql/data
    - ./volumes/postgres/db_backup:/backup

