tasmoadmin:
  container_name: tasmoadmin
  image: ghcr.io/tasmoadmin/tasmoadmin:latest
  restart: unless-stopped
  environment:
    - TZ=Etc/UTC
  ports:
    - "8088:80"
  volumes:
    - ./volumes/tasmoadmin/data:/data

