zigbee2mqtt_assistant:
  container_name: zigbee2mqtt_assistant
  image: carldebilly/zigbee2mqttassistant
  restart: unless-stopped
  ports:
    - "8880:80"
  environment:
    - VIRTUAL_HOST=~^zigbee2mqtt_assistant\..*\.xip\.io
    - Z2MA_SETTINGS__MQTTSERVER=mosquitto
    - VIRTUAL_PORT=8880

