domoticz:
  container_name: domoticz
  image: domoticz/domoticz:stable
  restart: unless-stopped
  environment:
    - TZ=${TZ:-Etc/UTC}
    # - LOG_PATH=/opt/domoticz/userdata/domoticz.log
    # - EXTRA_CMD_ARG=
  ports:
    - "8083:8080"
    - "1443:443"
  volumes:
    - ./volumes/domoticz:/opt/domoticz/userdata
  x-devices:
    - "/dev/serial/by-id/usb-0658_0200-if00-port0:/dev/ttyACM0"
