motioneye:
  image: dontobi/motioneye.rpi:latest
  container_name: "motioneye"
  restart: unless-stopped
  ports:
    - "8765:8765"
    - "8766:8081"
  environment:
    - TZ=${TZ:-Etc/UTC}
  volumes:
    - ./volumes/motioneye/etc_motioneye:/etc/motioneye
    - ./volumes/motioneye/var_lib_motioneye:/var/lib/motioneye

