prometheus-cadvisor:
  container_name: prometheus-cadvisor
  image: zcube/cadvisor:latest
  restart: unless-stopped
  ports:
    - "8082:8080"
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

