portainer-ce:
  container_name: portainer-ce
  image: portainer/portainer-ce
  restart: unless-stopped
  ports:
    - "8000:8000"
    - "9000:9000"
    # HTTPS
    - "9443:9443"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./volumes/portainer-ce/data:/data

