octoprint:
  container_name: octoprint
  image: octoprint/octoprint
  restart: unless-stopped
  environment:
    - TZ=${TZ:-Etc/UTC}
    # - ENABLE_MJPG_STREAMER=true
    # - MJPG_STREAMER_INPUT=-r 640x480 -f 10 -y
    # - CAMERA_DEV=/dev/video0
  ports:
    - "9980:80"
  devices:
    - "${OCTOPRINT_DEVICE_PATH:?eg echo OCTOPRINT_DEVICE_PATH=/dev/serial0 >>~/IOTstack/.env}:/dev/ttyACM0"
    # - /dev/video0:/dev/video0
  volumes:
    - ./volumes/octoprint:/octoprint

