dashmachine:
  image: rmountjoy/dashmachine:latest
  container_name: dashmachine
  volumes:
    - ./volumes/dashmachine/user_data:/dashmachine/dashmachine/user_data
  ports:
    - "5000:5000"
  restart: unless-stopped

