prometheus:
  container_name: prometheus
  build: ./.templates/prometheus/.
  restart: unless-stopped
  user: "0"
  ports:
    - "9090:9090"
  environment:
    - IOTSTACK_UID=1000
    - IOTSTACK_GID=1000
  volumes:
    - ./volumes/prometheus/data:/prometheus
  command:
    - '--config.file=/prometheus/config/config.yml'
    #    defaults are:
    #    - --config.file=/etc/prometheus/prometheus.yml
    #    - --storage.tsdb.path=/prometheus
    #    - --web.console.libraries=/usr/share/prometheus/console_libraries
    #    - --web.console.templates=/usr/share/prometheus/consoles
  depends_on:
    - prometheus-cadvisor
    - prometheus-nodeexporter

