homer:
  image: b4bz/homer:latest
  container_name: homer
  environment:
    - INIT_ASSETS=1
  user: $UID:$GID
  volumes:
    - ./volumes/homer/assets:/www/assets
  ports:
    - "8881:8080"
  restart: unless-stopped

