home_assistant:
  container_name: home_assistant
  image: ghcr.io/home-assistant/home-assistant:stable
  restart: unless-stopped
  network_mode: host
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./volumes/home_assistant:/config
  privileged: true
